version: '3.3'

services:
  mysql_db:
    image: mysql:8.0.23
    container_name: wa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@2021
    ports:
      - 3306:3306
    volumes:
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
      - wa_mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 4g
volumes: 
  wa_mysql_data: