version: 2.1
executors:
  j11:
    docker:
      - image: 'cimg/openjdk:11.0'
orbs:
  maven: circleci/maven@1.1
  jira: circleci/jira@1.3.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j11
      - build:
          post-steps:
            - jira/notify